import Phaser from 'phaser';
import { type P2PEntityState, type P2PInputMessage, type P2PSnapshotMessage, WebRtcSession } from '../net/WebRtcSession';

type Mode = 'practice' | 'host' | 'peer';
type Owner = 'host' | 'peer' | 'enemy';
interface InitData { mode?: Mode; session?: WebRtcSession; }
interface Weapon { name: string; damage: number; speed: number; rate: number; clip: number; reload: number; color: number; spread: number; radius: number; }
interface Fighter {
  sprite: Phaser.GameObjects.Sprite; x: number; y: number; vx: number; vy: number;
  aim: Phaser.Math.Vector2; move: number; jet: boolean; fire: boolean; alive: boolean;
  hp: number; fuel: number; respawn: number; spawnX: number; weapon: number; ammo: number;
  fireCd: number; reloadCd: number; kos: number; reloadSeq: number; appliedReloadSeq: number;
  aiCd?: number; aiFireCd?: number;
}
interface Shot { id: number; body: Phaser.GameObjects.Arc; glow: Phaser.GameObjects.Arc; x: number; y: number; vx: number; vy: number; life: number; damage: number; color: number; radius: number; owner: Owner; }

export class ArenaScene extends Phaser.Scene {
  private mode: Mode = 'practice'; private session?: WebRtcSession; private net = 'offline';
  private readonly ground = 570; private readonly weapons: Weapon[] = [
    { name:'Pulse Pistol', damage:18, speed:760, rate:.22, clip:12, reload:1.1, color:0x56efff, spread:.01, radius:6 },
    { name:'Burst Blaster', damage:11, speed:820, rate:.105, clip:20, reload:1.3, color:0xff6f9d, spread:.035, radius:5 },
    { name:'Cloud Cannon', damage:25, speed:590, rate:.44, clip:8, reload:1.45, color:0xd98bff, spread:.06, radius:9 },
    { name:'Shard Rifle', damage:34, speed:980, rate:.62, clip:6, reload:1.55, color:0x64baff, spread:.008, radius:7 },
    { name:'Nova Launcher', damage:44, speed:500, rate:.86, clip:4, reload:1.7, color:0xffd94f, spread:.035, radius:13 }
  ];
  private host!: Fighter; private peer!: Fighter; private local!: Fighter; private remote!: Fighter;
  private drones: Fighter[] = []; private shots: Shot[] = []; private nextShot = 1;
  private latestPeer: P2PInputMessage = { type:'input', seq:0, moveAxis:0, aimX:-1, aimY:0, jetpack:false, firing:false, weaponIndex:0, reloadSeq:0 };
  private snapshot?: P2PSnapshotMessage; private seq = 0; private sendInputTimer = 0; private sendSnapshotTimer = 0; private reloadSeq = 0;
  private keys!: Record<'left'|'right'|'jet'|'reload'|'prev'|'next'|'menu', Phaser.Input.Keyboard.Key>;
  private aim = new Phaser.Math.Vector2(980, 300); private firing = false;
  private hud!: Phaser.GameObjects.Text; private right!: Phaser.GameObjects.Text; private status!: Phaser.GameObjects.Text; private reticle!: Phaser.GameObjects.Container;
  private padBase?: Phaser.GameObjects.Arc; private padKnob?: Phaser.GameObjects.Arc; private jetButton?: Phaser.GameObjects.Container;
  private moveTouch: number|null = null; private aimTouch: number|null = null; private jetTouch: number|null = null;
  private moveOrigin = new Phaser.Math.Vector2(); private touchMove = 0; private touchFire = false; private touchJet = false;

  constructor(){ super('ArenaScene'); }
  init(data: InitData){ this.mode=data.mode??'practice'; this.session=data.session; }
  create(){ this.drawWorld(); this.createActors(); this.createHud(); this.createInput(); this.createNetwork(); this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.session?.close()); }
  update(_:number, ms:number){ const dt=Math.min(ms/1000,.05); this.readInput();
    if(this.mode==='practice'){ this.step(this.local,dt); this.stepBots(dt); this.stepShots(dt); }
    else if(this.mode==='host'){ this.applyPeerInput(); this.step(this.host,dt); this.step(this.peer,dt); this.tryFire(this.host,'host'); this.tryFire(this.peer,'peer'); this.stepShots(dt); this.publish(dt); }
    else { this.step(this.peer,dt); this.sendInput(dt); this.reconcile(); }
    this.reticle.setPosition(this.aim.x,this.aim.y); this.refreshHud();
  }

  private drawWorld(){ const g=this.add.graphics(); g.fillGradientStyle(0x63ccff,0x63ccff,0xe9fbff,0xf7d9ff,1).fillRect(0,0,1280,720); g.fillStyle(0xffec82).fillCircle(1160,85,48);
    for(const [x,y,s] of [[95,115,1.1],[430,165,.85],[900,120,1]] as const){ g.fillStyle(0xffffff,.85); g.fillCircle(x,y,25*s); g.fillCircle(x+32*s,y-10*s,34*s); g.fillCircle(x+70*s,y,27*s); }
    const land=this.add.graphics(); land.fillStyle(0x7bda64).fillRoundedRect(0,this.ground-28,1280,46,15); land.fillStyle(0x47a45a).fillRect(0,this.ground+6,1280,150);
    for(const [x,y] of [[235,390],[540,335],[865,395]]){ const p=this.add.graphics(); p.fillStyle(0xefffff,.94).fillRoundedRect(x,y,150,18,9); p.fillStyle(0x57c9ff,.9).fillRoundedRect(x+18,y+17,114,9,6); }
  }
  private fighter(x:number,tint:number){ const s=this.add.sprite(x,this.ground-64,'hero',0).setScale(1.25).setTint(tint).play('hero-idle'); return {sprite:s,x,y:this.ground,vx:0,vy:0,aim:new Phaser.Math.Vector2(1,0),move:0,jet:false,fire:false,alive:true,hp:100,fuel:100,respawn:0,spawnX:x,weapon:0,ammo:this.weapons[0].clip,fireCd:0,reloadCd:0,kos:0,reloadSeq:0,appliedReloadSeq:0} satisfies Fighter; }
  private createActors(){ this.host=this.fighter(210,0xfff0ff); this.peer=this.fighter(1040,0xc9f7ff); this.peer.aim.set(-1,0); this.local=this.mode==='peer'?this.peer:this.host; this.remote=this.mode==='peer'?this.host:this.peer;
    if(this.mode==='practice'){ this.peer.sprite.destroy(); this.drones=[this.fighter(855,0xd8c8ff),this.fighter(1060,0xc7ffe0)]; this.drones.forEach((d,i)=>{d.weapon=i+1;d.ammo=this.weapons[d.weapon].clip;d.aiCd=.4+i*.3;d.aiFireCd=.5+i*.2;}); }
    const r=this.add.graphics(); r.lineStyle(3,0xff58a7,.95).strokeCircle(0,0,13); r.lineBetween(-22,0,-8,0);r.lineBetween(22,0,8,0);r.lineBetween(0,-22,0,-8);r.lineBetween(0,22,0,8); this.reticle=this.add.container(this.aim.x,this.aim.y,[r]).setDepth(90);
  }
  private createHud(){ this.hud=this.add.text(22,18,'',{fontFamily:'Arial Black',fontSize:'19px',color:'#fff',stroke:'#2e5270',strokeThickness:6}).setDepth(100); this.right=this.add.text(1255,18,'',{fontFamily:'Arial',fontSize:'18px',color:'#294861',align:'right'}).setOrigin(1,0).setDepth(100); this.status=this.add.text(640,26,'',{fontFamily:'Arial Black',fontSize:'18px',color:'#fff',stroke:'#574b83',strokeThickness:5}).setOrigin(.5,0).setDepth(100); this.add.text(640,695,'Q/E weapon • R reload • M menu',{fontFamily:'Arial',fontSize:'17px',color:'#264861'}).setOrigin(.5,1).setDepth(100); this.createTouchUi(); }
  private createTouchUi(){ this.padBase=this.add.circle(115,610,66,0xffffff,.18).setDepth(100); this.padKnob=this.add.circle(115,610,32,0xffffff,.34).setDepth(101); const bg=this.add.graphics();bg.fillStyle(0x44d5ed,.88).fillRoundedRect(-50,-31,100,62,25);bg.lineStyle(4,0xffffff).strokeRoundedRect(-50,-31,100,62,25); const txt=this.add.text(0,0,'JET',{fontFamily:'Arial Black',fontSize:'25px',color:'#fff'}).setOrigin(.5); this.jetButton=this.add.container(1150,490,[bg,txt]).setDepth(101); this.add.text(1110,615,'HOLD + DRAG\nAIM / FIRE',{fontFamily:'Arial Black',fontSize:'18px',color:'#fff',align:'center',stroke:'#315578',strokeThickness:5}).setOrigin(.5).setAlpha(.75).setDepth(100); }
  private createInput(){ this.keys=this.input.keyboard!.addKeys({left:Phaser.Input.Keyboard.KeyCodes.A,right:Phaser.Input.Keyboard.KeyCodes.D,jet:Phaser.Input.Keyboard.KeyCodes.SPACE,reload:Phaser.Input.Keyboard.KeyCodes.R,prev:Phaser.Input.Keyboard.KeyCodes.Q,next:Phaser.Input.Keyboard.KeyCodes.E,menu:Phaser.Input.Keyboard.KeyCodes.M}) as typeof this.keys;
    this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{ if(p.id===this.moveTouch){const dx=Phaser.Math.Clamp(p.worldX-this.moveOrigin.x,-52,52);this.touchMove=dx/52;this.padKnob?.setPosition(this.moveOrigin.x+dx,this.moveOrigin.y);} if(p.id===this.aimTouch||p.pointerType==='mouse')this.aim.set(p.worldX,p.worldY); });
    this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{ if(this.jetButton?.getBounds().contains(p.worldX,p.worldY)){this.jetTouch=p.id;this.touchJet=true;return;} if(p.pointerType==='touch'&&p.worldX<400&&this.moveTouch===null){this.moveTouch=p.id;this.moveOrigin.set(p.worldX,p.worldY);this.padBase?.setPosition(p.worldX,p.worldY);this.padKnob?.setPosition(p.worldX,p.worldY);return;} this.aimTouch=p.id;this.aim.set(p.worldX,p.worldY);this.touchFire=true;if(p.pointerType==='mouse')this.firing=true; });
    this.input.on('pointerup',(p:Phaser.Input.Pointer)=>{if(p.id===this.moveTouch){this.moveTouch=null;this.touchMove=0;this.padBase?.setPosition(115,610);this.padKnob?.setPosition(115,610);} if(p.id===this.aimTouch){this.aimTouch=null;this.touchFire=false;this.firing=false;} if(p.id===this.jetTouch){this.jetTouch=null;this.touchJet=false;}});
  }
  private readInput(){ if(Phaser.Input.Keyboard.JustDown(this.keys.menu)){this.scene.start('MenuScene');return;} let m=(this.keys.left.isDown?-1:0)+(this.keys.right.isDown?1:0);if(Math.abs(this.touchMove)>Math.abs(m))m=this.touchMove; this.local.move=Phaser.Math.Clamp(m,-1,1);this.local.jet=this.keys.jet.isDown||this.touchJet;this.local.fire=this.firing||this.touchFire||this.input.activePointer.leftButtonDown();
    const a=this.aim.clone().subtract(new Phaser.Math.Vector2(this.local.x,this.local.y-64));if(a.lengthSq()>.001)this.local.aim.copy(a.normalize()); if(Phaser.Input.Keyboard.JustDown(this.keys.prev))this.switchWeapon(this.local,-1);if(Phaser.Input.Keyboard.JustDown(this.keys.next))this.switchWeapon(this.local,1);if(Phaser.Input.Keyboard.JustDown(this.keys.reload)){this.reloadSeq++;this.local.reloadSeq=this.reloadSeq;if(this.mode!=='peer')this.beginReload(this.local);} if(this.mode==='practice')this.tryFire(this.local,'host'); }

  private createNetwork(){ if(!this.session)return; this.net=this.session.connected?'connected':'connecting'; this.session.onState(s=>this.net=s); this.session.onMessage(msg=>{if(this.mode==='host'&&msg.type==='input')this.latestPeer=msg;else if(this.mode==='peer'&&msg.type==='snapshot')this.snapshot=msg;}); }
  private sendInput(dt:number){ if(!this.session)return;this.sendInputTimer+=dt;if(this.sendInputTimer<1/30)return;this.sendInputTimer=0;this.session.send({type:'input',seq:++this.seq,moveAxis:this.peer.move,aimX:this.peer.aim.x,aimY:this.peer.aim.y,jetpack:this.peer.jet,firing:this.peer.fire,weaponIndex:this.peer.weapon,reloadSeq:this.peer.reloadSeq}); }
  private applyPeerInput(){ const i=this.latestPeer;this.peer.move=i.moveAxis;this.peer.aim.set(i.aimX,i.aimY).normalize();this.peer.jet=i.jetpack;this.peer.fire=i.firing;this.peer.weapon=Phaser.Math.Clamp(i.weaponIndex,0,this.weapons.length-1);if(i.reloadSeq>this.peer.appliedReloadSeq){this.peer.appliedReloadSeq=i.reloadSeq;this.beginReload(this.peer);} }
  private publish(dt:number){ if(!this.session)return;this.sendSnapshotTimer+=dt;if(this.sendSnapshotTimer<1/20)return;this.sendSnapshotTimer=0;this.session.send({type:'snapshot',ackInputSeq:this.latestPeer.seq,host:this.netState(this.host),peer:this.netState(this.peer),projectiles:this.shots.map(s=>({id:s.id,x:s.x,y:s.y,color:s.color,radius:s.radius}))}); }
  private reconcile(){ if(!this.snapshot)return; const snap=this.snapshot;this.snapshot=undefined;this.applyNet(this.host,snap.host,false); const p=snap.peer;this.peer.x=Phaser.Math.Linear(this.peer.x,p.x,.25);this.peer.y=Phaser.Math.Linear(this.peer.y,p.y,.25);this.peer.vx=p.vx;this.peer.vy=p.vy;this.peer.hp=p.health;this.peer.fuel=p.fuel;this.peer.alive=p.alive;this.peer.ammo=p.ammo;this.peer.kos=p.koCount;this.peer.weapon=p.weaponIndex;this.updateSprite(this.peer); this.drawNetShots(snap.projectiles); }
  private netState(f:Fighter):P2PEntityState{return{x:f.x,y:f.y,vx:f.vx,vy:f.vy,aimX:f.aim.x,aimY:f.aim.y,health:f.hp,fuel:f.fuel,alive:f.alive,weaponIndex:f.weapon,ammo:f.ammo,koCount:f.kos};}
  private applyNet(f:Fighter,s:P2PEntityState,smooth=true){f.x=smooth?Phaser.Math.Linear(f.x,s.x,.35):s.x;f.y=smooth?Phaser.Math.Linear(f.y,s.y,.35):s.y;f.vx=s.vx;f.vy=s.vy;f.aim.set(s.aimX,s.aimY);f.hp=s.health;f.fuel=s.fuel;f.alive=s.alive;f.weapon=s.weaponIndex;f.ammo=s.ammo;f.kos=s.koCount;f.sprite.setVisible(s.alive);this.updateSprite(f);}
  private drawNetShots(states:{id:number;x:number;y:number;color:number;radius:number}[]){ for(const s of states){const key=`net-shot-${s.id}`;let c=this.children.getByName(key) as Phaser.GameObjects.Container|null;if(!c){c=this.add.container(s.x,s.y,[this.add.circle(0,0,s.radius+7,s.color,.3),this.add.circle(0,0,s.radius,0xffffff,1).setStrokeStyle(3,s.color)]).setName(key).setDepth(30);}c.setPosition(s.x,s.y);} const ids=new Set(states.map(s=>`net-shot-${s.id}`));for(const child of [...this.children.list])if(child.name.startsWith('net-shot-')&&!ids.has(child.name))child.destroy(); }

  private stepBots(dt:number){ for(const d of this.drones){if(!d.alive){this.respawn(d,dt);continue;}d.aiCd=(d.aiCd??0)-dt;if((d.aiCd??0)<=0){d.aiCd=Phaser.Math.FloatBetween(.6,1.3);d.move=Phaser.Math.Between(0,1)?1:-1;d.jet=Phaser.Math.Between(0,100)>72;}const v=new Phaser.Math.Vector2(this.local.x-d.x,this.local.y-d.y);if(v.lengthSq()>.01)d.aim.copy(v.normalize());d.aiFireCd=(d.aiFireCd??0)-dt;d.fire=(d.aiFireCd??0)<=0;if(d.fire)d.aiFireCd=Phaser.Math.FloatBetween(.2,.55);this.step(d,dt);this.tryFire(d,'enemy');} }
  private step(f:Fighter,dt:number){if(!f.alive){this.respawn(f,dt);return;}f.fireCd=Math.max(0,f.fireCd-dt);if(f.reloadCd>0){f.reloadCd=Math.max(0,f.reloadCd-dt);if(f.reloadCd<=.001)f.ammo=this.weapons[f.weapon].clip;}f.vx+=f.move*2050*dt;if(Math.abs(f.move)<.04)f.vx=Phaser.Math.Linear(f.vx,0,Math.min(1,dt*8));f.vx=Phaser.Math.Clamp(f.vx,-355,355);f.vy+=1560*dt;if(f.jet&&f.fuel>0){f.vy-=2110*dt;f.fuel=Math.max(0,f.fuel-27*dt);if(Phaser.Math.Between(0,100)>80)this.fx('fx-jet',f.x,f.y,0.62);}else f.fuel=Math.min(100,f.fuel+(f.y>=this.ground?34:12)*dt);f.vy=Phaser.Math.Clamp(f.vy,-720,760);f.x=Phaser.Math.Clamp(f.x+f.vx*dt,70,1210);f.y+=f.vy*dt;if(f.y>this.ground){f.y=this.ground;if(f.vy>0)f.vy=0;}this.updateSprite(f);}
  private updateSprite(f:Fighter){f.sprite.setPosition(f.x,f.y-64).setFlipX(f.aim.x<0);if(!f.alive)return;const a=f.y<this.ground-6||f.jet?'hero-fly':Math.abs(f.vx)>28?'hero-run':'hero-idle';if(f.sprite.anims.currentAnim?.key!==a&&f.sprite.anims.currentAnim?.key!=='hero-shoot')f.sprite.play(a);}
  private switchWeapon(f:Fighter,d:number){f.weapon=(f.weapon+d+this.weapons.length)%this.weapons.length;f.ammo=Math.min(f.ammo,this.weapons[f.weapon].clip);if(f.ammo<=0)f.ammo=this.weapons[f.weapon].clip;f.reloadCd=0;}
  private beginReload(f:Fighter){const w=this.weapons[f.weapon];if(f.alive&&f.reloadCd<=0&&f.ammo<w.clip)f.reloadCd=w.reload;}
  private tryFire(f:Fighter,owner:Owner){if(!f.alive||!f.fire)return;const w=this.weapons[f.weapon];if(f.fireCd>0||f.reloadCd>0)return;if(f.ammo<=0){this.beginReload(f);return;}f.fireCd=w.rate;f.ammo--;const angle=Math.atan2(f.aim.y,f.aim.x)+Phaser.Math.FloatBetween(-w.spread,w.spread);const x=f.x+Math.cos(angle)*55,y=f.y-67+Math.sin(angle)*24;const glow=this.add.circle(x,y,w.radius+7,w.color,.28).setDepth(30),body=this.add.circle(x,y,w.radius,0xffffff,1).setStrokeStyle(3,w.color).setDepth(31);this.shots.push({id:this.nextShot++,body,glow,x,y,vx:Math.cos(angle)*w.speed,vy:Math.sin(angle)*w.speed,life:w.name==='Nova Launcher'?1.65:1.3,damage:w.damage,color:w.color,radius:w.radius,owner});this.fx('fx-muzzle',x,y,.68,angle);f.sprite.play('hero-shoot');f.sprite.once(Phaser.Animations.Events.ANIMATION_COMPLETE,()=>{if(f.alive)f.sprite.play('hero-idle');});if(f.ammo<=0)this.beginReload(f);}
  private stepShots(dt:number){for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.body.setPosition(s.x,s.y);s.glow.setPosition(s.x,s.y);let rm=s.life<=0||s.x<-80||s.x>1360||s.y<-80||s.y>800;if(!rm){if(this.mode==='practice'){if(s.owner==='host'){for(const d of this.drones)if(this.hit(s,d)){this.damage(d,s.damage,this.local);rm=true;break;}}else if(s.owner==='enemy'&&this.hit(s,this.local)){this.damage(this.local,s.damage);rm=true;}}else{const t=s.owner==='host'?this.peer:this.host;if(this.hit(s,t)){this.damage(t,s.damage,s.owner==='host'?this.host:this.peer);rm=true;}}}if(rm){this.fx('fx-impact',s.x,s.y,.65);s.body.destroy();s.glow.destroy();this.shots.splice(i,1);}}}
  private hit(s:Shot,f:Fighter){return f.alive&&Phaser.Math.Distance.Between(s.x,s.y,f.x,f.y-65)<35+s.radius;}
  private damage(t:Fighter,n:number,a?:Fighter){if(!t.alive)return;t.hp=Math.max(0,t.hp-n);if(t.hp>0)return;t.alive=false;t.respawn=2;t.vx=t.vy=0;if(a)a.kos++;t.sprite.play('hero-ko');this.time.delayedCall(750,()=>{if(!t.alive)t.sprite.setVisible(false);});}
  private respawn(f:Fighter,dt:number){f.respawn-=dt;if(f.respawn>0)return;f.alive=true;f.hp=f.fuel=100;f.x=f.spawnX;f.y=this.ground;f.vx=f.vy=0;f.ammo=this.weapons[f.weapon].clip;f.reloadCd=0;f.sprite.setVisible(true).play('hero-idle');this.fx('fx-respawn',f.x,f.y-45,.95);}
  private fx(key:string,x:number,y:number,scale:number,rot=0){const e=this.add.sprite(x,y,'effects').setScale(scale).setRotation(rot).setDepth(40).play(key);e.once(Phaser.Animations.Events.ANIMATION_COMPLETE,()=>e.destroy());}
  private refreshHud(){const w=this.weapons[this.local.weapon];this.hud.setText([w.name,`AMMO ${this.local.ammo}/${w.clip}${this.local.reloadCd>0?`  RELOAD ${this.local.reloadCd.toFixed(1)}s`:''}`,`HP ${Math.ceil(this.local.hp)}   JET ${Math.ceil(this.local.fuel)}`,`KOs ${this.local.kos}`]);if(this.mode==='practice'){this.status.setText('PRACTICE ARENA');this.right.setText(this.drones.map((d,i)=>`DRONE ${i+1}: ${d.alive?`${Math.ceil(d.hp)} HP`:'RESPAWN'}`).join('\n'));}else{this.status.setText(`${this.mode.toUpperCase()} • ${this.net.toUpperCase()}`);this.right.setText(`Opponent HP ${Math.ceil(this.remote.hp)}\nOpponent KOs ${this.remote.kos}\nWebRTC direct P2P`);}}
}
