import Phaser from 'phaser';
import { arenaById, drawArena, modeById, physicsFor } from '../game/Maps';
import { WEAPONS } from '../game/Weapons';
import type { InputBatchMessage, LobbyPlayer, MatchConfig, MatchEndMessage, PlayerId, PlayerInputSample, PlayerStateNet, ProjectileStateNet, SnapshotMessage } from '../net/Protocol';
import { WebRtcMesh } from '../net/WebRtcMesh';
import { InputHistory, simulateMovement, StateInterpolator } from '../sim/Simulation';

type Role='practice'|'host'|'peer';
interface Init{role?:Role;session?:WebRtcMesh;config?:MatchConfig;lobbyPlayers?:LobbyPlayer[];localPlayerId?:PlayerId;}
interface Fighter{id:PlayerId;name:string;sprite:Phaser.GameObjects.Sprite;x:number;y:number;vx:number;vy:number;aimX:number;aimY:number;health:number;fuel:number;alive:boolean;respawnMs:number;weaponIndex:number;ammo:number;score:number;fire:number;reload:number;reloadSeq:number;appliedReloadSeq:number;spawnX:number;jet:boolean;ai:number;strafe:number;}
interface Shot{id:number;ownerId:PlayerId;x:number;y:number;vx:number;vy:number;life:number;damage:number;color:number;radius:number;body:Phaser.GameObjects.Arc;glow:Phaser.GameObjects.Arc;}
const TINT:Record<PlayerId,number>={1:0xffffff,2:0xcff7ff,3:0xffd1ec,4:0xddffd4};

export class ArenaScene extends Phaser.Scene{
 private role:Role='practice';private session?:WebRtcMesh;private config:MatchConfig={mapId:'sky-garden',modeId:'ffa',scoreLimit:10};private lobby:LobbyPlayer[]=[];private localId:PlayerId=1;
 private fighters=new Map<PlayerId,Fighter>();private shots:Shot[]=[];private shotId=1;private physics=physicsFor(this.config);private rules=modeById(this.config.modeId);private queues=new Map<PlayerId,PlayerInputSample[]>();private ack:Partial<Record<PlayerId,number>>={};private history=new InputHistory();private interpolators=new Map<PlayerId,StateInterpolator>();private outbound:PlayerInputSample[]=[];private seq=0;private reloadSeq=0;private inputTimer=0;private snapTimer=0;private tick=0;private ended=false;private cleanup:Array<()=>void>=[];
 private keys!:Record<'left'|'right'|'jet'|'reload'|'prev'|'next'|'menu',Phaser.Input.Keyboard.Key>;private aim=new Phaser.Math.Vector2(980,300);private firing=false;
 private moveBase?:Phaser.GameObjects.Arc;private moveKnob?:Phaser.GameObjects.Arc;private aimBase?:Phaser.GameObjects.Arc;private aimKnob?:Phaser.GameObjects.Arc;private reticle?:Phaser.GameObjects.Container;private hud?:Phaser.GameObjects.Text;private scores?:Phaser.GameObjects.Text;private bars?:Phaser.GameObjects.Graphics;private net?:Phaser.GameObjects.Text;
 private movePointer:number|null=null;private aimPointer:number|null=null;private jetPointer:number|null=null;private moveOrigin=new Phaser.Math.Vector2();private aimOrigin=new Phaser.Math.Vector2();private touchAxis=0;private touchAim=new Phaser.Math.Vector2(1,0);private touchJet=false;private touchFire=false;
 constructor(){super('ArenaScene');}
 init(d:Init):void{this.role=d.role??'practice';this.session=d.session;this.config=d.config??{mapId:'sky-garden',modeId:'ffa',scoreLimit:10};this.lobby=d.lobbyPlayers??[{id:1,name:'Sky Explorer',ready:true,connected:true,isHost:true}];this.localId=d.localPlayerId??1;this.physics=physicsFor(this.config);this.rules=modeById(this.config.modeId);this.fighters.clear();this.shots=[];this.queues.clear();this.interpolators.clear();this.history.clear();this.outbound=[];this.seq=0;this.reloadSeq=0;this.ended=false;}
 create():void{drawArena(this,this.config);this.createFighters();this.createHud();this.createControls();this.bindNetwork();this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{this.cleanup.forEach(f=>f());this.cleanup=[];});}
 update(_:number,ms:number):void{if(this.ended)return;const dt=Math.min(ms/1000,.05);this.cooldowns(dt);const input=this.capture(dt);if(this.role==='practice'){this.apply(this.local(),input,true);this.bots(dt);this.stepShots(dt);this.respawns(dt);this.checkWin();}else if(this.role==='host'){this.apply(this.local(),input,true);this.peerInputs();this.stepShots(dt);this.respawns(dt);this.publish(dt);this.checkWin();}else{this.predict(input);this.sendInputs(dt);this.interpolate();}this.renderFighters();this.renderHud();this.reticle?.setPosition(this.aim.x,this.aim.y);}
 private createFighters():void{const arena=arenaById(this.config.mapId);const players=this.role==='practice'&&this.lobby.length<4?[{id:1,name:'Sky Explorer',ready:true,connected:true,isHost:true},{id:2,name:'Mochi Bot',ready:true,connected:true,isHost:false},{id:3,name:'Nova Bot',ready:true,connected:true,isHost:false},{id:4,name:'Pip Bot',ready:true,connected:true,isHost:false}]as LobbyPlayer[]:this.lobby;for(const p of players){const x=arena.spawnXs[p.id-1],wi=this.rules.forcedWeapon??((p.id-1)%WEAPONS.length),sprite=this.add.sprite(x,this.physics.groundY-64,'hero',0).setScale(1.25).setTint(TINT[p.id]).play('hero-idle');this.fighters.set(p.id,{id:p.id,name:p.name,sprite,x,y:this.physics.groundY,vx:0,vy:0,aimX:p.id===1?1:-1,aimY:0,health:100,fuel:100,alive:true,respawnMs:0,weaponIndex:wi,ammo:WEAPONS[wi].clipSize,score:0,fire:0,reload:0,reloadSeq:0,appliedReloadSeq:0,spawnX:x,jet:false,ai:.4,strafe:p.id%2===0?-1:1});this.queues.set(p.id,[]);this.interpolators.set(p.id,new StateInterpolator());}const g=this.add.graphics();g.lineStyle(3,0xff5ca8,.95).strokeCircle(0,0,13);g.lineBetween(-22,0,-8,0);g.lineBetween(22,0,8,0);g.lineBetween(0,-22,0,-8);g.lineBetween(0,22,0,8);this.reticle=this.add.container(this.aim.x,this.aim.y,[g]).setDepth(120);}
 private createHud():void{this.bars=this.add.graphics().setDepth(110);this.hud=this.add.text(22,66,'',{fontFamily:'Arial Black',fontSize:'17px',color:'#fff',stroke:'#2f506d',strokeThickness:5}).setDepth(110);this.scores=this.add.text(1255,58,'',{fontFamily:'Arial',fontSize:'17px',color:'#29465f',align:'right',lineSpacing:7}).setOrigin(1,0).setDepth(110);this.net=this.add.text(640,52,'',{fontFamily:'Arial Black',fontSize:'15px',color:'#fff',stroke:'#5c4a7a',strokeThickness:4}).setOrigin(.5,0).setDepth(110);}
 private button(x:number,y:number,label:string,color:number,down:()=>void):Phaser.GameObjects.Container{const c=this.add.container(x,y).setDepth(125),g=this.add.graphics();g.fillStyle(color,.78).fillRoundedRect(-45,-26,90,52,20);g.lineStyle(3,0xffffff,.9).strokeRoundedRect(-45,-26,90,52,20);c.add([g,this.add.text(0,0,label,{fontFamily:'Arial Black',fontSize:'15px',color:'#fff'}).setOrigin(.5)]);c.setSize(90,52).setInteractive();c.on('pointerdown',(p:Phaser.Input.Pointer)=>{p.event.stopPropagation();down();});return c;}
 private createControls():void{this.keys=this.input.keyboard!.addKeys({left:Phaser.Input.Keyboard.KeyCodes.A,right:Phaser.Input.Keyboard.KeyCodes.D,jet:Phaser.Input.Keyboard.KeyCodes.SPACE,reload:Phaser.Input.Keyboard.KeyCodes.R,prev:Phaser.Input.Keyboard.KeyCodes.Q,next:Phaser.Input.Keyboard.KeyCodes.E,menu:Phaser.Input.Keyboard.KeyCodes.M})as typeof this.keys;this.moveBase=this.add.circle(112,615,66,0xffffff,.16).setDepth(120);this.moveKnob=this.add.circle(112,615,31,0xffffff,.34).setDepth(121);this.aimBase=this.add.circle(1115,615,66,0xffffff,.16).setDepth(120);this.aimKnob=this.add.circle(1115,615,31,0xff83c5,.34).setDepth(121);const jet=this.button(1060,480,'JET',0x45d7ef,()=>this.touchJet=true),swap=this.button(1180,450,'SWAP',0xb776eb,()=>this.switchWeapon(1)),rld=this.button(940,450,'RLD',0x63c77d,()=>this.triggerReload());jet.on('pointerup',()=>this.touchJet=false);jet.on('pointerout',()=>this.touchJet=false);void swap;void rld;
  this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(p.x<360&&p.y>420&&this.movePointer===null){this.movePointer=p.id;this.moveOrigin.set(p.x,p.y);this.moveBase?.setPosition(p.x,p.y);this.moveKnob?.setPosition(p.x,p.y);return;}if(p.x>700&&p.y>360&&this.aimPointer===null){this.aimPointer=p.id;this.aimOrigin.set(p.x,p.y);this.touchFire=true;return;}if(p.pointerType!=='touch')sthis.firing=true;});
  this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(p.id===this.movePointer){const dx=Phaser.Math.Clamp(p.x-this.moveOrigin.x,-55,55);this.touchAxis=dx/55;this.moveKnob?.setPosition(this.moveOrigin.x+dt,this.moveOrigin.y);}if(p.id===this.aimPointer){const v=new Phaser.Math.Vector2(p.x-this.aimOrigin.x,p.y-this.aimOrigin.y);if(v.length()>8)this.touchAim=v.normalize();this.aimKnob?.setPosition(this.aimOrigin.x+this.touchAim.x*45,this.aimOrigin.y+this.touchAim.y*45);}if(p.pointerType!=='touch')this.aim.set(p.x,p.y);});
  this.input.on('pointerup',(p:Phaser.Input.Pointer)=>{if(p.id===this.movePointer){this.movePointer=null;this.touchAxis=0;this.moveBase?.setPosition(112,615);this.moveKnob?.setPosition(112,615);}if(p.id===this.aimPointer){this.aimPointer=null;this.touchFire=false;this.aimBase?.setPosition(1115,615);this.aimKnob?.setPosition(1115,615);}if(p.id===this.jetPointer){this.jetPointer=null;this.touchJet=false;}if(p.pointerType!=='touch')this.firing=false;});}
 private capture(dt:number):PlayerInputSample{if(Phaser.Input.Keyboard.JustDown(this.keys.prev))this.switchWeapon(-1);if(Phaser.Input.Keyboard.JustDown(this.keys.next))this.switchWeapon(1);if(Phaser.Input.Keyboard.JustDown(this.keys.reload))this.triggerReload();if(Phaser.Input.Keyboard.JustDown(this.keys.menu)){this.session?.close();this.scene.start('MenuScene');}let axis=(this.keys.left.isDown?-1:0)+(this.keys.right.isDown?1:0);if(Math.abs(this.touchAxis)>Math.abs(axis))axis=this.touchAxis;const l=this.local();let ax:number,ay:number;if(this.aimPointer!==null){ax=this.touchAim.x;ay=this.touchAim.y;this.aim.set(l.x+ax*180,l.y-64+ay*180);}else{const v=new Phaser.Math.Vector2(this.aim.x-l.x,this.aim.y-(l.y-64));if(v.lengthSq()<1)v.set(l.aimX,l.aimY);v.normalize();ax=v.x;ay=v.y;}return{seq:++this.seq,dt,moveAxis:axis,aimX:ax,aimY:ay,jetpack:this.keys.jet.isDown||this.touchJet,firing:this.firing||this.touchFire||this.input.activePointer.leftButtonDown(),weaponIndex:l.weaponIndex,reloadSeq:this.reloadSeq};}
 private apply(f:Fighter,i:PlayerInputSample,authority:boolean):void{f.aimX=i.aimX;f.aimY=i.aimY;f.jet=i.jetpack;f.weaponIndex=this.rules.forcedWeapon??Phaser.Math.Clamp(i.weaponIndex,0,WEAPONS.length-1);simulateMovement(f,i,this.physics);if(authority&&i.reloadSeq>f.appliedReloadSeq){f.appliedReloadSeq=i.reloadSeq;this.beginReload(f);}if(authority&&i.firing)this.fire(f);}
 private predict(i:PlayerInputSample):void{const l=this.local();this.history.push(i);this.outbound.push(i);if(this.outbound.length>12)this.outbound.splice(0,this.outbound.length-12);this.apply(l,i,false);}
 private sendInputs(dt:number):void{if(!this.session)