import Phaser from 'phaser';
import { ARENAS, MODES } from '../game/Maps';
import type { LobbyPlayer, MatchConfig, PlayerId, ReliableMessage } from '../net/Protocol';
import { WebRtcMesh } from '../net/WebRtcMesh';

type LobbyRole='practice'|'host'|'peer';
interface LobbyInit{role?:LobbyRole;session?:WebRtcMesh;roomCode?:string;playerName?:string;}

export class LobbyScene extends Phaser.Scene{
  private role:LobbyRole='practice';private session?:WebRtcMesh;private roomCode='PRACTICE';private playerName='Sky Explorer';
  private players:LobbyPlayer[]=[];private config:MatchConfig={mapId:'sky-garden',modeId:'ffa',scoreLimit:10};
  private listText?:Phaser.GameObjects.Text;private configText?:Phaser.GameObjects.Text;private statusText?:Phaser.GameObjects.Text;private readyButtonText?:Phaser.GameObjects.Text;private localReady=false;private cleanup:Array<()=>void>=[];
  constructor(){super('LobbyScene');}
  init(data:LobbyInit):void{this.role=data.role??'practice';this.session=data.session;this.roomCode=data.roomCode??'PRACTICE';this.playerName=data.playerName??'Sky Explorer';this.localReady=this.role==='practice';this.players=[{id:1,name:this.role==='peer'?'Host':this.playerName,ready:this.role==='practice',connected:true,isHost:true}];}
  create():void{this.drawBackdrop();this.createUi();this.bindNetwork();this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{for(const off of this.cleanup)off();this.cleanup=[];});this.render();}
  private drawBackdrop():void{const g=this.add.graphics();g.fillGradientStyle(0x6fd4ff,0x6fd4ff,0xf5ddff,0xf5ddff,1).fillRect(0,0,1280,720);g.fillStyle(0xffffff,.26).fillRoundedRect(115,90,1050,545,38);this.add.image(640,605,'weapons').setScale(.85).setAlpha(.28);}
  private createUi():void{
    this.add.text(640,50,this.role==='practice'?'PRACTICE SETUP':`ROOM ${this.roomCode}`,{fontFamily:'Arial Black',fontSize:'38px',color:'#fff',stroke:'#315171',strokeThickness:8}).setOrigin(.5);
    this.add.text(255,125,'PLAYERS',{fontFamily:'Arial Black',fontSize:'25px',color:'#315171'});this.listText=this.add.text(255,170,'',{fontFamily:'Arial',fontSize:'24px',color:'#29465f',lineSpacing:14});
    this.add.text(690,125,'MATCH',{fontFamily:'Arial Black',fontSize:'25px',color:'#315171'});this.configText=this.add.text(690,170,'',{fontFamily:'Arial',fontSize:'23px',color:'#29465f',lineSpacing:12});
    if(this.role!=='peer'){this.addSmallButton(760,330,'◀ MAP',0x6d9cff,()=>this.cycleMap(-1));this.addSmallButton(955,330,'MAP ▶',0x6d9cff,()=>this.cycleMap(1));this.addSmallButton(760,395,'◀ MODE',0xb678e9,()=>this.cycleMode(-1));this.addSmallButton(955,395,'MODE ▶',0xb678e9,()=>this.cycleMode(1));this.addSmallButton(760,460,'− SCORE',0x58c98b,()=>this.changeScore(-5));this.addSmallButton(955,460,'+ SCORE',0x58c98b,()=>this.changeScore(5));}
    if(this.role!=='practice'){const ready=this.add.container(330,520),bg=this.add.graphics();bg.fillStyle(0xff68aa,1).fillRoundedRect(-135,-31,270,62,25);bg.lineStyle(4,0xffffff).strokeRoundedRect(-135,-31,270,62,25);this.readyButtonText=this.add.text(0,0,'READY',{fontFamily:'Arial Black',fontSize:'23px',color:'#fff'}).setOrigin(.5);ready.add([bg,this.readyButtonText]);ready.setSize(270,62).setInteractive({useHandCursor:true});ready.on('pointerup',()=>this.toggleReady());}
    if(this.role!=='peer'){const start=this.add.container(850,535),bg=this.add.graphics();bg.fillStyle(0x52c979,1).fillRoundedRect(-170,-34,340,68,28);bg.lineStyle(4,0xffffff).strokeRoundedRect(-170,-34,340,68,28);start.add([bg,this.add.text(0,0,'START MATCH',{fontFamily:'Arial Black',fontSize:'25px',color:'#fff'}).setOrigin(.5)]);start.setSize(340,68).setInteractive({useHandCursor:true});start.on('pointerup',()=>this.startMatch());}
    this.statusText=this.add.text(640,666,'',{fontFamily:'Arial',fontSize:'18px',color:'#315171',align:'center'}).setOrigin(.5);this.addSmallButton(118,54,'← MENU',0x657d97,()=>{this.session?.close();this.scene.start('MenuScene');},150);
  }
  private addSmallButton(x:number,y:number,label:string,color:number,action:()=>void,width=170):void{const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(color,.96).fillRoundedRect(-width/2,-25,width,50,20);g.lineStyle(3,0xffffff,.9).strokeRoundedRect(-width/2,-25,width,50,20);c.add([g,this.add.text(0,0,label,{fontFamily:'Arial Black',fontSize:'17px',color:'#fff'}).setOrigin(.5)]);c.setSize(width,50).setInteractive({useHandCursor:true});c.on('pointerup',action);}
  private bindNetwork():void{if(!this.session)return;this.cleanup.push(this.session.onStatus((status,detail)=>this.statusText?.setText(`${status.toUpperCase()}${detail?` • ${detail}`:''}`)));this.cleanup.push(this.session.onPeer((id,connected)=>{if(this.role==='host'&&!connected){this.players=this.players.filter((p)=>p.id!==id);this.broadcastLobby();}}));this.cleanup.push(this.session.onReliable((from,msg)=>this.onReliable(from,msg)));}
  private onReliable(from:PlayerId,message:ReliableMessage):void{if(this.role==='host'){if(message.type==='hello'){const existing=this.players.find((p)=>p.id===from);if(existing)existing.name=message.name;else this.players.push({id:from,name:message.name,ready:false,connected:true,isHost:false});this.broadcastLobby();}if(message.type==='ready'){const p=this.players.find((e)=>e.id===from);if(p)p.ready=message.ready;this.broadcastLobby();}return;}if(message.type==='lobby-state'){this.players=message.players;this.config=message.config;this.roomCode=message.roomCode;this.render();}if(message.type==='start-match'){this.scene.start('ArenaScene',{role:'peer',session:this.session,config:message.config,lobbyPlayers:message.players,localPlayerId:this.session?.localPlayerId??2});}}
  private toggleReady():void{this.localReady=!this.localReady;this.readyButtonText?.setText(this.localReady?'READY ✓':'READY');if(this.role==='host'){const host=this.players.find((p)=>p.id===1);if(host)host.ready=this.localReady;this.broadcastLobby();}else this.session?.sendReliable({type:'ready',ready:this.localReady});this.render();}
  private cycleMap(direction:number):void{const i=ARENAS.findIndex((a)=>a.id===this.config.mapId);this.config.mapId=ARENAS[(i+direction+ARENAS.length)%ARENAS.length].id;this.broadcastLobby();}
  private cycleMode(direction:number):void{const i=MODES.findIndex((m)=>m.id===this.config.modeId);this.config.modeId=MODES[(i+direction+MODES.length)%MODES.length].id;this.broadcastLobby();}
  private changeScore(delta:number):void{this.config.scoreLimit=Phaser.Math.Clamp(this.config.scoreLimit+delta,5,30);this.broadcastLobby();}
  private broadcastLobby():void{if(this.role==='host')this.session?.sendReliable({type:'lobby-state',players:this.players,config:this.config,roomCode:this.roomCode});this.render();}
  private startMatch():void{if(this.role==='practice'){const p:LobbyPlayer[]=[{id:1,name:this.playerName,ready:true,connected:true,isHost:true},{id:2,name:'Mochi Bot',ready:true,connected:true,isHost:false},{id:3,name:'Nova Bot',ready:true,connected:true,isHost:false},{id:4,name:'Pip Bot',ready:true,connected:true,isHost:false}];this.scene.start('ArenaScene',{role:'practice',config:this.config,lobbyPlayers:p,localPlayerId:1});return;}if(this.role!=='host')return;const connected=this.players.filter((p)=>p.connected);if(connected.length<2){this.statusText?.setText('At least 2 players are required.');return;}if(connected.some((p)=>!p.ready)){this.statusText?.setText('All connected players must be ready.');return;}this.session?.sendReliable({type:'start-match',players:connected,config:this.config});this.scene.start('ArenaScene',{role:'host',session:this.session,config:this.config,lobbyPlayers:connected,localPlayerId:1});}
  private render():void{const entries=[1,2,3,4].map((id)=>{const p=this.players.find((e)=>e.id===id);if(!p)return`○ Slot ${id} — waiting`;return`${p.isHost?'★':'●'} P${id}  ${p.name}  —  ${p.ready?'READY ✓':'not ready'}`;});this.listText?.setText(entries.join('\n'));const arena=ARENAS.find((e)=>e.id===this.config.mapId)??ARENAS[0],mode=MODES.find((e)=>e.id===this.config.modeId)??MODES[0];this.configText?.setText([`Map: ${arena.name}`,`Mode: ${mode.name}`,`Score limit: ${this.config.scoreLimit} KOs`,'',mode.description].join('\n'));if(this.role==='host'){const host=this.players.find((p)=>p.id===1);if(host)host.ready=this.localReady;}}
}
